#!/usr/bin/env bash
set -euo pipefail

CELL="${1:?cell required: POLICY, INTEGER, or COMBINED}"
RUN_ID="${DISTILL_RUN_ID:-phase-d-20260903a}"
POLICY_MODEL="${DISTILL_POLICY_MODEL:-phase-m-h64-policy-1m}"
BASE_MODEL="${DISTILL_BASE_MODEL:-phase-e-c40-h64-frozen}"
WORKERS="${BENCH_WORKERS:-16}"

case "$CELL" in
  POLICY)
    MODEL="$POLICY_MODEL"
    CANDIDATE_SEARCH=policy-see
    CANDIDATE_RUNTIME=reference
    ;;
  INTEGER)
    MODEL="$BASE_MODEL"
    CANDIDATE_SEARCH=see
    CANDIDATE_RUNTIME=integer
    ;;
  COMBINED)
    MODEL="$POLICY_MODEL"
    CANDIDATE_SEARCH=policy-see
    CANDIDATE_RUNTIME=integer
    ;;
  *)
    echo "cell must be POLICY, INTEGER, or COMBINED" >&2
    exit 2
    ;;
esac

shutdown_host() {
  if [[ "${BENCH_SHUTDOWN:-1}" == "1" ]]; then
    sudo shutdown -h +1
  fi
}
trap shutdown_host EXIT

run_match() {
  local nodes="$1" rounds="$2"
  DISTILL_RUN_ID="$RUN_ID" \
  DISTILL_MODEL_NAME="$MODEL" \
  DISTILL_VARIANT_NAME="phase-n-${CELL,,}" \
  DISTILL_OPPONENT_MODEL_NAME="$MODEL" \
  DISTILL_CANDIDATE_ANTISYMMETRIC=1 \
  DISTILL_OPPONENT_ANTISYMMETRIC=1 \
  DISTILL_CANDIDATE_SEARCH="$CANDIDATE_SEARCH" \
  DISTILL_CANDIDATE_RUNTIME="$CANDIDATE_RUNTIME" \
  DISTILL_OPPONENT_SEARCH=see \
  DISTILL_OPPONENT_RUNTIME=reference \
  BENCH_FIXED_NODES="$nodes" \
  BENCH_ROUNDS="$rounds" \
  BENCH_WORKERS="$WORKERS" \
  BENCH_SHUTDOWN=0 \
    bash infra/aws/benchmark-distilled.sh
}

run_match 1000 "${BENCH_1K_ROUNDS:-20}"
run_match 10000 "${BENCH_10K_ROUNDS:-5}"

DISTILL_RUN_ID="$RUN_ID" \
DISTILL_MODEL_NAME="$MODEL" \
DISTILL_VARIANT_NAME="phase-n-${CELL,,}-clock" \
DISTILL_OPPONENT_MODEL_NAME="$MODEL" \
DISTILL_CANDIDATE_ANTISYMMETRIC=1 \
DISTILL_OPPONENT_ANTISYMMETRIC=1 \
DISTILL_CANDIDATE_SEARCH="$CANDIDATE_SEARCH" \
DISTILL_CANDIDATE_RUNTIME="$CANDIDATE_RUNTIME" \
DISTILL_OPPONENT_SEARCH=see \
DISTILL_OPPONENT_RUNTIME=reference \
BENCH_BASE_MS="${BENCH_BASE_MS:-5000}" \
BENCH_ROUNDS="${BENCH_CLOCK_ROUNDS:-10}" \
BENCH_WORKERS="$WORKERS" \
BENCH_SHUTDOWN=0 \
  bash infra/aws/benchmark-distilled.sh
