#!/usr/bin/env bash
set -euo pipefail

export DISTILL_RUN_ID="${DISTILL_RUN_ID:-phase-q-20260906a}"
export TEACHER_WORKER_COUNT="${TEACHER_WORKER_COUNT:-80}"
export DISTILL_PART_POSITIONS="${DISTILL_PART_POSITIONS:-5000000}"
export DISTILL_PART_SHARDS="${DISTILL_PART_SHARDS:-1250}"
export DISTILL_SOURCES_PER_WORKER="${DISTILL_SOURCES_PER_WORKER:-8}"
export DISTILL_FIRST_SOURCE_SHARD="${DISTILL_FIRST_SOURCE_SHARD:-133}"
export DISTILL_SEED="${DISTILL_SEED:-20260907}"
export DISTILL_EXCLUDE_RUNS="${DISTILL_EXCLUDE_RUNS:-pilot-20260831a eval-20260901a scale-20260901a phase-c-20260902a phase-d-20260903a}"

export TEACHER_SHARDS="${TEACHER_SHARDS:-100000}"
export TEACHER_NODES="${TEACHER_NODES:-100000}"
export TEACHER_PARALLELISM="${TEACHER_PARALLELISM:-32}"
export PHASE_D_LABEL_WAIT_LIMIT="${PHASE_D_LABEL_WAIT_LIMIT:-11520}"
export PHASE_D_COORDINATE="${PHASE_D_COORDINATE:-0}"

export DISTILL_BASE_RUN_ID="${DISTILL_BASE_RUN_ID:-phase-d-20260903a}"
export DISTILL_TOTAL_SHARDS="${DISTILL_TOTAL_SHARDS:-100000}"
export DISTILL_EXPECTED_RECORDS="${DISTILL_EXPECTED_RECORDS:-400000000}"
export DISTILL_BASE_RECORDS="${DISTILL_BASE_RECORDS:-100000000}"
export DISTILL_DATASET_NAME="${DISTILL_DATASET_NAME:-phase-q-extra-400m}"
export DISTILL_BASE_COMPONENTS="${DISTILL_BASE_COMPONENTS:-phase-c-base-1m phase-c-extra-2m phase-c-extra-7m phase-d-extra-90m}"
export DISTILL_BUILD_WORKERS="${DISTILL_BUILD_WORKERS:-32}"

exec bash infra/aws/phase-d-label.sh "$@"
